### PR TITLE
Issue #240

### PR DESCRIPTION
**Pull request by baris5d**
**What does this PR do?**
This PR solves https://github.com/OpenSouceCode/Frontend/issues/240 issue.

I re-defined shadow sizes, blurs and colors in a better way. 
Changed the padding, color and shadow of Filters sidebar. Now all shadows look same. 
Grids in organizations page had smaller gap, it looks more understandable right now.
Issue and Pull Request list elements had big font sizes I've contained Issue/PR number, owner, and dates with small tag.

**Affected Pages**
Feed
Organizations
Starred Repositories
Project

### CODE REVIEW

**Review by vipulsnp — CHANGES_REQUESTED** [review]
**UI breaking** on `Organizations` Page
image
`Reduce Padding`
image

`Add` the color to starred repositories which was there earlier.  in `Starred Repos` & `Feed` page.

**Doesn't give a nicer look*

image
since the previous one was better 
Previous One: 
image

**Comment by baris5d** [comment]
I restored the background color for starred repositories page. I was changed the unit of grids from 32% 32% 32% to 1fr 1fr 1fr. I forgot the breakpoints, sorry. I've changed them also. And reduced the padding.  

After you gave me a review I realized that I did reset the margin-right for repository owner images but I didn't do the same for starred repositories. Now, It's okay too.

**Review by vipulsnp — CHANGES_REQUESTED** [review]
The UI for organizations page is still breaking.

**Comment by baris5d** [comment]
If you mean selected part of following image by telling still breaking I've nothing done with it, even in first commit. I changed the gap size. It looks good on mobile right now. I checked all breakpoints and I didn't get that result. If you mean anything else could you please specify the breakpoints and the results?
image

**Comment by vipulsnp** [comment]
On hosted site it is fine at all breakpoints. Check that

**Comment by baris5d** [comment]
First images are local, second ones belong hosted one. I do not see anything wrong. I wonder you mean anything else I do not realize. I took screenshots with same boxes you sent.


iPhone
iphone

1920x1080
1920x1080

1366x768
1366x768

1175x768
1175x768

**Comment by vipulsnp** [comment]
@baris5d Check `fedora project` organization at 1244px in hosted site and localhost. You will notice the difference . I am attaching the screenshot for that
**localhost**
image
**Hosted**
image

**Comment by baris5d** [comment]
I fixed the problem by reducing the gap on a breakpoint but it happens only in Mozilla Firefox browser. It's already exist in hosted page but we cannot see the problem because box has enough space to hide it. Overflow doesn't work properly, there's only one line and the second line should be hidden. Other browsers hide the second line even if less than half of the text is wrapped by tags. But Mozilla shows the top of text in a way. 

Browsers I've tested: Chrome, Opera, Mozilla

**Review by vipulsnp — APPROVED** [review]

**Pull request merged**
