### PR TITLE
add header and footer file on style.css #6

### PR DESCRIPTION
**Pull request by Akashsingh310**
This PR solves issue #

**What does this PR do?**

**Any background context you want to provide?**

**Screenshots?**

### CODE REVIEW

**Comment by Akashsingh310** [comment]
Text align center on Footer REACH OUT TO US ON.
And added  header and footer file on style.css

**Comment by irshadjsr21** [comment]
@Akashsingh310 Can you make the links on footer visible?

**Comment by Akashsingh310** [comment]
**footer links** are visible now

**Comment by irshadjsr21** [comment]
Don't add any colors, just keep all the text and icons black. Also undo other changes.

**Comment by Akashsingh310** [comment]
I have just make footer background black because image was white so the the  link will be  visible and added a className of centered .

Footer change image

**Comment by irshadjsr21** [comment]
@Akashsingh310 The footer design has been updated by our UI/UX team, you might want to join our slack channel to keep up with the project. 
I'll be closing this PR but you can pick other issues to work on. Just comment on an issue and it'll be assigned to you.

**Pull request closed without merging**
