### PR TITLE
fixed width issue of input tag of search bar

### PR DESCRIPTION
**Pull request by nihalbaig0**
This PR solves issue #179

it solved the input tag width of search bar.

### CODE REVIEW

**Comment by Dishebh** [comment]
@nihalbaig0 There's already an open PR for it. #180

**Comment by Dishebh** [comment]
Also, you don't have to push the env variables along with the change

**Comment by nihalbaig0** [comment]
Thanks for the review. Do I have to select another Issue that hasn't been PR yet?

**Comment by Dishebh** [comment]
@nihalbaig0 yep, that would be great :)

**Comment by vipulsnp** [comment]
The issue mentioned in this PR is already resolved..

**Pull request closed without merging**
