### PR TITLE
Solved the issue 216

### PR DESCRIPTION
**Pull request by mahakal420**
This PR solves issue #

**What does this PR do?**
It has solved the issue 216

**Any background context you want to provide?**

**Screenshots?**

### CODE REVIEW

**Review by vipulsnp — CHANGES_REQUESTED** [review]
Not only the buttons are to be changed.
Also change how the selections are made.
**Current Error**
image

**Comment by vipulsnp** [comment]
@mahakal420  Update ?

**Comment by mahakal420** [comment]
Hey vipul,I have made some changes in code but when I click on sign with
github button on my local host it is giving me 404 error So I am not able
to see the feed.Could you please help me with this?

**Comment by Dishebh** [comment]
@mahakal420 can you share the screenshot of the error?

**Comment by mahakal420** [comment]
> @mahakal420 can you share the screenshot of the error?

I have mailed you the screenshot.

**Comment by Dishebh** [comment]
> > @mahakal420 can you share the screenshot of the error?
> 
> I have mailed you the screenshot.

The isaue should be solved now :)

**Pull request merged**
